# This file will hold the functions for your 'Verifier Fleet'.
# e.g., def check_graph_validity(graph): ...
# e.g., def check_math_execution(step_text): ...
# These will be used by the 02_verify_data.py script.
